# Generated by Django 4.1.2 on 2022-10-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
